### PR TITLE
rover PR

### PR DESCRIPTION
**Pull request by wmpay**
@glebinsky

### CODE REVIEW

**Comment by glebinsky** [comment]
Hey Max can you finish #3.

**Comment by wmpay** [comment]
Sure, late night last night sorry bout that.

**Comment by militantwalrus** [comment]
Gleb, someone...

For no clear reason, I'm getting emailed these comments. My user 'militantwalrus' doesn't have an ICS repositiories anymore, so I'm not sure why this is happening. Could someone look into it and make sure that user is discociated from ICS?

Thanks.

**Comment by jabyrd3** [comment]
@glebinsky the way i was doing it was `rm -rf .git; git init; git set remote...` and then forwarding the fresh repo to avoid cross chatter situations like this. Anybody's who has ever touched the repo is getting notifications.

@militantwalrus in the meantime, you can use the 'Unsubscribe' button to the right of the comment form to make sure you don't get any more notifications.

**Comment by wmpay** [comment]
@glebinsky fixed

**Comment by glebinsky** [comment]
@jabyrd3 was militantwalrus the only other one to make a pr to this repo besides me and wmpay? just wondering why i'm only seeing us 4 as participants after the last round of interviews.

**Comment by glebinsky** [comment]
Hey Max, just got word that we're shifting focus with the front-end role to be senior level at minimum. I think you have the skills and smarts but we need more experience with big apps. Back-end isn't being pursued in the short-term or we'd bring you in for a face-to-face. If you're interested, ADP Innovation Labs has some really smart and fun people who I still keep in touch with. Otherwise, best of luck in your search.

**Pull request closed without merging**
